// src/routes/(auth)/sign-up-complete/+page.svelte
<script lang="ts">
	import Button from '$lib/components/ui/button/button.svelte';
	import { Check } from 'lucide-svelte';
</script>

<div class="flex flex-col items-center space-y-6">
	<div class="bg-muted relative flex h-20 w-20 items-center justify-center rounded-full">
		<Check class="h-8 w-8 text-green-500" />
	</div>

	<div class="flex flex-col space-y-2 text-center">
		<h1 class="text-xl font-semibold">Signup Complete!</h1>
		<p class="text-muted-foreground text-sm">You have successfully created your account.</p>
	</div>

	<Button href="/login" class="w-full rounded-full font-medium text-white">Next</Button>
</div>

// src/app/(auth)/sign-up-complete/page.tsx
import { Check } from 'lucide-react'
import { Button } from '@/components/ui/button'
import Link from 'next/link'

export default function SignUpCompletePage() {
  return (
    <div className="flex flex-col items-center space-y-6">
      <div className="bg-muted relative flex h-20 w-20 items-center justify-center rounded-full">
        <Check className="h-8 w-8 text-green-500" />
      </div>

      <div className="flex flex-col space-y-2 text-center">
        <h1 className="text-xl font-semibold">Signup Complete!</h1>
        <p className="text-muted-foreground text-sm">You have successfully created your account.</p>
      </div>

      <Button asChild className="w-full rounded-full font-medium text-white">
        <Link href="/login">Next</Link>
      </Button>
    </div>
  )
}
