// src/app/(app)/store/page.tsx
import { Plus } from 'lucide-react'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs'
import { DashboardHeader } from '@/components/header/dashboard-header'
import Link from 'next/link'

export default function StorePage() {
  return (
    <>
      <DashboardHeader
        description="Take full control of your store's design and vibe with our intuitive, powerful store builder."
        heading="Your Store"
        backHref="/settings"
      />

      <Tabs defaultValue="store">
        <div className="w-full">
          <TabsList>
            <TabsTrigger value="store">Store</TabsTrigger>
            <TabsTrigger value="blogs">Blog posts</TabsTrigger>
            <TabsTrigger value="domains">Domains</TabsTrigger>
          </TabsList>
        </div>

        <TabsContent value="store">
          <Card>
            <CardContent className="space-y-2">
              <div className="flex flex-col items-center space-y-2 text-center">
                <Button
                  className="flex h-10 w-10 items-center justify-center rounded-full bg-gray-100 p-0 text-gray-700 hover:bg-gray-300"
                  asChild
                >
                  <Link href={"/store/create-store" as any}>
                    <Plus className="h-4 w-4" />
                  </Link>
                </Button>

                <h1 className="text-xl">Create Store</h1>
                <p className="pb-4 text-sm text-gray-700">
                  Set Up Your Online Store and Start Selling Today
                </p>

                <Button asChild>
                  <Link href={"/store/create-store" as any}>Create</Link>
                </Button>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="blogs">
          <Card>
            <CardContent className="space-y-2">
              <div className="flex flex-col items-center space-y-2 text-center">
                <Button
                  className="flex h-10 w-10 items-center justify-center rounded-full bg-gray-100 p-0 text-gray-700 hover:bg-gray-300"
                  asChild
                >
                  <Link href={"/store/blogs/add" as any}>
                    <Plus className="h-4 w-4" />
                  </Link>
                </Button>

                <h1 className="text-xl">Add Blog Post</h1>
                <p className="pb-4 text-sm text-gray-700">
                  Start Creating a New Blog Post to Share Your Insights and Expertise
                </p>

                <Button asChild>
                  <Link href={"/store/blogs/add" as any}>Add Blog Post</Link>
                </Button>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="domains">
          <Card>
            <CardContent className="space-y-2">
              <div className="flex flex-col items-center space-y-2 text-center">
                <Button
                  className="flex h-10 w-10 items-center justify-center rounded-full bg-gray-100 p-0 text-gray-700 hover:bg-gray-300"
                  asChild
                >
                  <Link href={"/store/domains" as any}>
                    <Plus className="h-4 w-4" />
                  </Link>
                </Button>

                <h1 className="text-xl">Connect to existing domain</h1>
                <p className="pb-4 text-sm text-gray-700">
                  Already Have a Domain? Connect It to Your Site Here
                </p>

                <Button asChild>
                  <Link href={"/store/domains" as any}>Connect</Link>
                </Button>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </>
  )
}

// src/routes/(app)/store/+page.svelte
<script lang="ts">
	import { Plus } from 'lucide-svelte';

	import * as Tabs from '$lib/components/ui/tabs';
	import * as Card from '$lib/components/ui/card';
	import { Button } from '$lib/components/ui/button';
	import { DashboardHeader } from '$lib/components/header';
</script>

<DashboardHeader
	description="Take full control of your store's design and vibe with our intuitive, powerful store builder."
	heading="Your Store"
	backHref="/settings"
/>

<Tabs.Root value="store">
	<div class="w-full">
		<Tabs.List>
			<Tabs.Trigger value="store">Store</Tabs.Trigger>
			<Tabs.Trigger value="blogs">Blog posts</Tabs.Trigger>
			<Tabs.Trigger value="domains">Domains</Tabs.Trigger>
		</Tabs.List>
	</div>

	<Tabs.Content value="store">
		<Card.Root>
			<Card.Content class="space-y-2">
				<div class="flex flex-col items-center space-y-2 text-center">
					<Button
						class="flex h-10 w-10 items-center justify-center rounded-full bg-gray-100 p-0 text-gray-700 hover:bg-gray-300"
						href="/store/create-store"
					>
						<Plus class="h-4 w-4" />
					</Button>

					<h1 class="text-xl">Create Store</h1>
					<p class=" pb-4 text-sm text-gray-700">
						Set Up Your Online Store and Start Selling Today
					</p>

					<Button href="/store/create-store">Create</Button>
				</div>
			</Card.Content>
		</Card.Root>
	</Tabs.Content>

	<Tabs.Content value="blogs">
		<Card.Root>
			<Card.Content class="space-y-2">
				<div class="flex flex-col items-center space-y-2 text-center">
					<Button
						class="flex h-10 w-10 items-center justify-center rounded-full bg-gray-100 p-0 text-gray-700 hover:bg-gray-300"
						href="/store/blogs/add"
					>
						<Plus class="h-4 w-4" />
					</Button>

					<h1 class="text-xl">Add Blog Post</h1>
					<p class=" pb-4 text-sm text-gray-700">
						Start Creating a New Blog Post to Share Your Insights and Expertise
					</p>

					<Button href="/store/blogs/add">Add Blog Post</Button>
				</div>
			</Card.Content>
		</Card.Root>
	</Tabs.Content>

	<Tabs.Content value="domains">
		<Card.Root>
			<Card.Content class="space-y-2">
				<div class="flex flex-col items-center space-y-2 text-center">
					<Button
						class="flex h-10 w-10 items-center justify-center rounded-full bg-gray-100 p-0 text-gray-700 hover:bg-gray-300"
						href="/store/domains"
					>
						<Plus class="h-4 w-4" />
					</Button>

					<h1 class="text-xl">Connect to existing domain</h1>
					<p class=" pb-4 text-sm text-gray-700">
						Already Have a Domain? Connect It to Your Site Here
					</p>

					<Button href="/store/domains">Connect</Button>
				</div>
			</Card.Content>
		</Card.Root>
	</Tabs.Content>
</Tabs.Root>
