// src/app/(app)/products/page.tsx
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Plus } from 'lucide-react'
import Link from 'next/link'

export default function ProductsPage() {
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Products</h1>
          <p className="text-muted-foreground">
            Manage your products and inventory
          </p>
        </div>
        <Button asChild>
          <Link href={"/products/add-new-product" as any}>
            <Plus className="mr-2 h-4 w-4" />
            Add Product
          </Link>
        </Button>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {/* Placeholder for products */}
        <Card>
          <CardHeader>
            <CardTitle className="text-lg">No products yet</CardTitle>
            <CardDescription>
              Start by adding your first product to the marketplace
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Button asChild className="w-full">
              <Link href={"/products/add-new-product" as any}>
                <Plus className="mr-2 h-4 w-4" />
                Add Your First Product
              </Link>
            </Button>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}

// src/routes/(app)/products/+page.svelte
<script lang="ts">
	import { Plus } from 'lucide-svelte';

	import * as Tabs from '$lib/components/ui/tabs/index.js';
	import * as Card from '$lib/components/ui/card/index.js';
	import { Button } from '$lib/components/ui/button/index.js';
</script>

<Tabs.Root value="products">
	<Tabs.List class="grid w-full grid-cols-3">
		<Tabs.Trigger value="products">Products</Tabs.Trigger>
		<Tabs.Trigger value="collaborators">Collaborators</Tabs.Trigger>
		<Tabs.Trigger value="reviews">Reviews</Tabs.Trigger>
	</Tabs.List>

	<Tabs.Content value="products">
		<Card.Root>
			<Card.Content class="space-y-2">
				<div class="flex flex-col items-center space-y-2 text-center">
					<Button
						class="flex h-10 w-10 items-center justify-center rounded-full bg-gray-100 p-0 text-gray-700 hover:bg-gray-300"
						href="/products/create-product"
					>
						<Plus class="h-4 w-4" />
					</Button>

					<h1 class="text-xl">Add Products</h1>
					<p class=" pb-4 text-sm text-gray-700">
						Turn your creativity into profit by adding and selling your digital products
						effortlessly.
					</p>

					<Button href="/products/create-product">Add Products</Button>
				</div>
			</Card.Content>
		</Card.Root>
	</Tabs.Content>

	<Tabs.Content value="collaborators">
		<Card.Root>
			<Card.Header>
				<Card.Title class="text-gray-700"></Card.Title>
			</Card.Header>
		</Card.Root>
	</Tabs.Content>

	<Tabs.Content value="reviews">
		<Card.Root>
			<Card.Header>
				<Card.Title class="text-gray-700"></Card.Title>
			</Card.Header>
		</Card.Root>
	</Tabs.Content>
</Tabs.Root>
