// src/components/header/dashboard-header.tsx
'use client'

import * as React from 'react'
import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'
import { Button } from '@/components/ui/button'

interface DashboardHeaderProps {
  heading: string
  description?: string
  backHref?: string
}

export function DashboardHeader({ heading, description, backHref }: DashboardHeaderProps) {
  return (
    <div className="flex items-center gap-4 mb-6">
      {backHref && (
        <Button variant="ghost" size="icon" asChild>
          <Link href={backHref}>
            <ArrowLeft className="h-4 w-4" />
          </Link>
        </Button>
      )}
      <div>
        <h1 className="text-2xl font-bold tracking-tight">{heading}</h1>
        {description && (
          <p className="text-muted-foreground">{description}</p>
        )}
      </div>
    </div>
  )
}

// src/lib/components/header/dashboard-header.svelte
<script lang="ts">
	import { ArrowLeftIcon } from 'lucide-svelte';

	import { Button } from '$lib/components/ui/button';
	import type { HTMLAttributes } from 'svelte/elements';
	import { cn } from '$lib/utils';

	type Props = HTMLAttributes<HTMLDivElement> & {
		heading: string;
		description?: string;
		backHref?: `/${string}`;
	};

	let {
		class: className,
		heading,
		description,
		children,
		backHref = '/home',
		...restProps
	}: Props = $props();
</script>

<div class={cn('flex items-center justify-between', className)} {...restProps}>
	<div class="flex items-start gap-x-4">
		<Button href={backHref} variant="secondary" class="rounded-full">
			<ArrowLeftIcon />
		</Button>
		<div class="space-y-1">
			<h3 class="text-xl font-semibold">{heading}</h3>
			{#if description}
				<p class="text-muted-foreground text-sm">
					{description}
				</p>
			{/if}
		</div>
	</div>
	{@render children?.()}
</div>
