// src/modules/app/components/app-sidebar.svelte
<script lang="ts">
	import { BookOpen, Settings } from 'lucide-svelte';

	import { links } from '..';

	import { getCurrentUser, urlRedirectForLoggedInUser } from '$modules/auth';
	import { goto } from '$app/navigation';
	import { page } from '$app/state';
	import { cn } from '$lib/utils';
	import * as Sidebar from '$lib/components/ui/sidebar';

	const { user } = getCurrentUser();
	const currentPath = $derived(page.url.pathname);
</script>

<Sidebar.Root
	class="mt-4 ml-4 flex h-[calc(100vh-32px)] w-[240px] flex-col justify-between rounded-md bg-white py-4"
>
	<Sidebar.Header class="mb-8">
		<Sidebar.Menu>
			<Sidebar.MenuItem>
				<Sidebar.MenuButton
					onclick={() => goto(urlRedirectForLoggedInUser(user))}
					isActive={true}
					class="text-muted-foreground flex h-10 items-center justify-center text-xl"
				>
					LOGO
				</Sidebar.MenuButton>
			</Sidebar.MenuItem>
		</Sidebar.Menu>
	</Sidebar.Header>

	<Sidebar.Content class="flex-1 overflow-y-auto px-2">
		<Sidebar.Group>
			<Sidebar.GroupContent>
				<Sidebar.Menu class="space-y-1">
					{#each links as link (link.title)}
						<Sidebar.MenuItem>
							<Sidebar.MenuButton
								isActive={currentPath.startsWith(link.url)}
								class="flex items-center gap-3 rounded-full px-4 py-2 text-sm transition-colors hover:bg-blue-50 hover:text-blue-600 data-[active=true]:bg-blue-50 data-[active=true]:text-blue-600"
							>
								{#snippet child({ props })}
									<a href={link.url} {...props}>
										<link.icon class="h-5 w-5" />
										<span>{link.title}</span>
									</a>
								{/snippet}
							</Sidebar.MenuButton>
						</Sidebar.MenuItem>
					{/each}
				</Sidebar.Menu>
			</Sidebar.GroupContent>
		</Sidebar.Group>
	</Sidebar.Content>

	<Sidebar.Footer class="px-2 pb-4">
		<Sidebar.Menu class="space-y-1">
			<Sidebar.MenuItem>
				<Sidebar.MenuButton
					isActive={currentPath.startsWith('/settings')}
					class="flex items-center gap-3 rounded-md px-4 py-2 text-sm transition-colors hover:bg-blue-50 hover:text-blue-600 data-[active=true]:bg-blue-50 data-[active=true]:text-blue-600"
				>
					<a href="/settings" class="flex w-full items-center gap-3">
						<Settings class="h-5 w-5" />
						<span>Settings</span>
					</a>
				</Sidebar.MenuButton>
			</Sidebar.MenuItem>
			<Sidebar.MenuItem>
				<Sidebar.MenuButton
					class="flex items-center gap-3 rounded-md px-4 py-2 text-sm transition-colors hover:bg-blue-50 hover:text-blue-600 data-[active=true]:bg-blue-50 data-[active=true]:text-blue-600"
				>
					<a href="/help" class="flex w-full items-center gap-3">
						<BookOpen class="h-5 w-5" />
						<span>Help</span>
					</a>
				</Sidebar.MenuButton>
			</Sidebar.MenuItem>
		</Sidebar.Menu>
	</Sidebar.Footer>
</Sidebar.Root>

// src/app/(app)/_components/app-sidebar.tsx
'use client'

import * as React from 'react'
import Link from 'next/link'
import { usePathname } from 'next/navigation'
import {
  Sidebar,
  SidebarContent,
  SidebarHeader,
  SidebarMenu,
  SidebarMenuItem,
  SidebarMenuButton,
  SidebarFooter,
  SidebarGroup,
  SidebarGroupContent,
} from '@/components/ui/sidebar'
import { 
  Home,
  Store,
  ShoppingBag,
  Users,
  Mail,
  Workflow,
  CircleDollarSign,
  TrendingUp,
  Library,
  Settings,
  BookOpen
} from 'lucide-react'
import { cn } from '@/lib/utils'

const links = [
  {
    title: 'Home',
    url: '/home',
    icon: Home,
  },
  {
    title: 'Products', 
    url: '/products',
    icon: Store,
  },
  {
    title: 'Store',
    url: '/store', 
    icon: ShoppingBag,
  },
  {
    title: 'Collaborators',
    url: '/collaborators',
    icon: Users,
  },
  {
    title: 'Checkout',
    url: '/checkout',
    icon: ShoppingBag,
  },
  {
    title: 'Emails',
    url: '/emails',
    icon: Mail,
  },
  {
    title: 'Workflows',
    url: '/workflows',
    icon: Workflow,
  },
  {
    title: 'Sales',
    url: '/sales',
    icon: CircleDollarSign,
  },
  {
    title: 'Analytics',
    url: '/analytics',
    icon: TrendingUp,
  },
  {
    title: 'Payouts',
    url: '/payouts', 
    icon: CircleDollarSign,
  },
  {
    title: 'Library',
    url: '/library',
    icon: Library,
  },
]

export function AppSidebar() {
  const pathname = usePathname()

  return (
    <Sidebar className="!w-[300px] mt-4 ml-4 flex h-[calc(100vh-32px)] flex-col justify-between rounded-md bg-white py-6">
      <SidebarHeader className="mb-8">
        <SidebarMenu>
          <SidebarMenuItem>
            <SidebarMenuButton asChild>
              <Link
                href="/home"
                className="text-muted-foreground flex h-10 items-center justify-center text-xl font-medium"
              >
                LOGO
              </Link>
            </SidebarMenuButton>
          </SidebarMenuItem>
        </SidebarMenu>
      </SidebarHeader>

      <SidebarContent className="flex-1 overflow-y-auto px-2">
        <SidebarGroup>
          <SidebarGroupContent>
            <SidebarMenu className="space-y-1">
              {links.map((link) => {
                const isActive = pathname.startsWith(link.url)
                return (
                  <SidebarMenuItem key={link.title}>
                    <SidebarMenuButton asChild>
                      <Link
                        href={link.url as any}
                        className={cn(
                          "h-8 flex items-center gap-3 rounded-full px-4 py-2 text-sm transition-colors hover:bg-blue-50 hover:text-blue-600 w-full data-[active=true]:bg-blue-50 data-[active=true]:text-blue-600",
                          isActive && "bg-blue-50 text-blue-600"
                        )}
                      >
                        <link.icon className="h-5 w-5 flex-shrink-0" />
                        <span className="truncate">{link.title}</span>
                      </Link>
                    </SidebarMenuButton>
                  </SidebarMenuItem>
                )
              })}
            </SidebarMenu>
          </SidebarGroupContent>
        </SidebarGroup>
      </SidebarContent>

      <SidebarFooter className="px-2 pb-4">
        <SidebarMenu className="space-y-1">
          <SidebarMenuItem>
            <SidebarMenuButton
              className={cn(
                "flex items-center gap-3 rounded-md px-4 py-2 text-sm transition-colors hover:bg-blue-50 hover:text-blue-600",
                pathname.startsWith('/settings') && "bg-blue-50 text-blue-600"
              )}
            >
              <Link href={"/settings" as any} className="flex w-full items-center gap-3">
                <Settings className="h-5 w-5 flex-shrink-0" />
                <span className="truncate">Settings</span>
              </Link>
            </SidebarMenuButton>
          </SidebarMenuItem>
          <SidebarMenuItem>
            <SidebarMenuButton className="flex items-center gap-3 rounded-md px-4 py-2 text-sm transition-colors hover:bg-blue-50 hover:text-blue-600">
              <Link href={"/help" as any} className="flex w-full items-center gap-3">
                <BookOpen className="h-5 w-5 flex-shrink-0" />
                <span className="truncate">Help</span>
              </Link>
            </SidebarMenuButton>
          </SidebarMenuItem>
        </SidebarMenu>
      </SidebarFooter>
    </Sidebar>
  )
}
