// src/modules/auth/forgot-password/forgot-password-form.svelte
<script lang="ts">
	import { defaults, superForm } from 'sveltekit-superforms';
	import { zod, zodClient } from 'sveltekit-superforms/adapters';
	import { createMutation } from '@tanstack/svelte-query';
	import { toast } from 'svelte-sonner';
	import { Eye, EyeOff, Loader2Icon } from 'lucide-svelte';

	import { forgotPassword, forgotPasswordSchema } from '..';
	import { goto } from '$app/navigation';

	import { Input } from '$lib/components/ui/input';
	import * as Form from '$lib/components/ui/form';
	import Button from '$lib/components/ui/button/button.svelte';

	const forgotPasswordMutation = createMutation({
		mutationKey: ['forgot-password'],
		mutationFn: forgotPassword,
		onSuccess: () => {
			toast.success('Password reset successfully!');
			goto('/login');
		},
		onError: (e) => {
			if (e.status === 422) {
				toast.error('Invalid OTP Code');
				return;
			}
			toast.error(e.message);
		}
	});

	const form = superForm(defaults(zod(forgotPasswordSchema)), {
		SPA: true,
		validators: zodClient(forgotPasswordSchema),
		onUpdate: ({ form }) => {
			if (form.valid) {
				$forgotPasswordMutation.mutate(form.data);
			}
		}
	});

	const { form: formData, enhance } = form;

	let showPassword = false;
	let showConfirmPassword = false;
</script>

<div class="flex flex-col pb-6">
	<h1 class="text-2xl font-semibold">Create New Password</h1>
	<p class="text-muted-foreground text-sm">We sent authentication to</p>
</div>

<form method="POST" use:enhance class="space-y-4">
	<Form.Field {form} class="w-full" name="password">
		<Form.Control>
			{#snippet children({ props })}
				<Form.Label>New Password</Form.Label>
				<div class="relative">
					<Input
						{...props}
						type={showPassword ? 'text' : 'password'}
						bind:value={$formData.password}
						placeholder="Enter New Password"
						class="rounded-full pr-10"
					/>

					<button
						type="button"
						class="text-muted-foreground hover:text-foreground absolute top-1/2 right-2 -translate-y-1/2"
						onclick={() => (showPassword = !showPassword)}
						tabindex="-1"
					>
						{#if showPassword}
							<Eye class="size-4" />
						{:else}
							<EyeOff class="size-4" />
						{/if}
					</button>
				</div>
			{/snippet}
		</Form.Control>
		<Form.FieldErrors />
	</Form.Field>

	<Form.Field {form} class="w-full" name="confirmPassword">
		<Form.Control>
			{#snippet children({ props })}
				<Form.Label>Re-enter New Password</Form.Label>
				<div class="relative">
					<Input
						{...props}
						type={showConfirmPassword ? 'text' : 'password'}
						bind:value={$formData.confirmPassword}
						placeholder="Re-enter New Password"
						class="rounded-full pr-10"
					/>

					<button
						type="button"
						class="text-muted-foreground hover:text-foreground absolute top-1/2 right-2 -translate-y-1/2"
						onclick={() => (showConfirmPassword = !showConfirmPassword)}
						tabindex="-1"
					>
						{#if showConfirmPassword}
							<Eye class="size-4" />
						{:else}
							<EyeOff class="size-4" />
						{/if}
					</button>
				</div>
			{/snippet}
		</Form.Control>
		<Form.FieldErrors />
	</Form.Field>

	<Form.Button
		disabled={$forgotPasswordMutation.isPending}
		class="w-full rounded-full font-medium text-white"
	>
		{#if $forgotPasswordMutation.isPending}
			<Loader2Icon class="mr-2 size-4 animate-spin" />
			Submitting...
		{:else}
			Next
		{/if}
	</Form.Button>
</form>

// src/components/auth/forgot-password-form.tsx
'use client'

import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { useMutation } from '@tanstack/react-query'
import { useRouter } from 'next/navigation'
import { Eye, EyeOff, Loader2 } from 'lucide-react'
import toast from 'react-hot-toast'

import { forgotPassword } from '@/lib/auth/mutations'
import { forgotPasswordSchema, type ForgotPasswordSchema } from '@/lib/auth/schemas'

import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form'

export function ForgotPasswordForm() {
  const router = useRouter()
  const [showPassword, setShowPassword] = useState(false)
  const [showConfirmPassword, setShowConfirmPassword] = useState(false)

  const form = useForm<ForgotPasswordSchema>({
    resolver: zodResolver(forgotPasswordSchema),
    defaultValues: {
      code: '',
      password: '',
      confirmPassword: '',
    },
  })

  const forgotPasswordMutation = useMutation({
    mutationKey: ['forgot-password'],
    mutationFn: forgotPassword,
    onSuccess: () => {
      toast.success('Password reset successfully!')
      router.push('/login')
    },
    onError: (error: any) => {
      if (error.status === 422) {
        toast.error('Invalid OTP Code')
        return
      }
      toast.error(error.message || 'An error occurred')
    },
  })

  const onSubmit = (data: ForgotPasswordSchema) => {
    // Remove confirmPassword from the data sent to API
    const { confirmPassword, ...submitData } = data
    forgotPasswordMutation.mutate(submitData)
  }

  return (
    <>
      <div className="flex flex-col pb-6">
        <h1 className="text-2xl font-semibold">Create New Password</h1>
      </div>

      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
          <FormField
            control={form.control}
            name="code"
            render={({ field }) => (
              <FormItem>
                <FormLabel>OTP Code</FormLabel>
                <FormControl>
                  <Input
                    type="text"
                    placeholder="Enter OTP Code"
                    className="rounded-full"
                    {...field}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="password"
            render={({ field }) => (
              <FormItem>
                <FormLabel>New Password</FormLabel>
                <FormControl>
                  <div className="relative">
                    <Input
                      type={showPassword ? 'text' : 'password'}
                      placeholder="Enter New Password"
                      className="rounded-full pr-10"
                      {...field}
                    />
                    <button
                      type="button"
                      className="text-muted-foreground hover:text-foreground absolute top-1/2 right-2 -translate-y-1/2"
                      onClick={() => setShowPassword(!showPassword)}
                      tabIndex={-1}
                    >
                      {showPassword ? (
                        <Eye className="size-4" />
                      ) : (
                        <EyeOff className="size-4" />
                      )}
                    </button>
                  </div>
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="confirmPassword"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Re-enter New Password</FormLabel>
                <FormControl>
                  <div className="relative">
                    <Input
                      type={showConfirmPassword ? 'text' : 'password'}
                      placeholder="Re-enter New Password"
                      className="rounded-full pr-10"
                      {...field}
                    />
                    <button
                      type="button"
                      className="text-muted-foreground hover:text-foreground absolute top-1/2 right-2 -translate-y-1/2"
                      onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                      tabIndex={-1}
                    >
                      {showConfirmPassword ? (
                        <Eye className="size-4" />
                      ) : (
                        <EyeOff className="size-4" />
                      )}
                    </button>
                  </div>
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <Button
            type="submit"
            className="w-full rounded-full font-medium text-white"
            disabled={forgotPasswordMutation.isPending}
          >
            {forgotPasswordMutation.isPending ? (
              <>
                <Loader2 className="mr-2 size-4 animate-spin" />
                Submitting...
              </>
            ) : (
              'Next'
            )}
          </Button>
        </form>
      </Form>
    </>
  )
}
